[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/netlify/*"
  to = "/404.html"
  status = 404
  force = true

[[headers]]
  for = "/works/bilingual-study/*"
  [headers.values]
    Content-Security-Policy = "connect-src 'self';"
